### ISSUE TITLE
Move OpenAPI 3 request coercions outside `:parameters`

### ISSUE THREAD

**Issue by opqdonut** [metosin/reitit#627]
# Currently

- Mix of `:body` and `:schema`
- Defaults on different level of nesting compared to per-content-type stuff
- Can't add per-content-type extra fields like `:examples`

```clj
["/foo" {:post {:parameters {:request {:content {"application/json" <schema>}
                                       :body <schema>}
                             ;; OR
                             :body <schema>}
                :responses {200 {:description ...
                                 :content {"application/json" {:schema <schema>}}
                                 :body <schema>}}}}]
```

# New format

```clj
["/foo" {:post {:request {:description ...
                          :content {"application/json" {:schema <schema>
                                                        :examples ...}
                                    :default {:schema <schema>}}}
                :parameters {:body <schema>}   ;; still supported for backwards compatibility & simple use cases
                :responses {200 {:description ...
                                 :content {"application/json" {:schema <schema>
                                                               :examples ...}
                                           :default {:schema <schema>}}
                                 :body <schema>}}}] ;; still supported for backwards compatibility?
```

Benefits:
- More symmetry between `:request` and `:responses`
- Can give OpenAPI3 multiple examples directly, without resorting to `:openapi`
- Future-proofing:
  - could support per-content-type `:handler`s
  
# TODO
- [x] implementation
  - [x] use new format in coercions
  - [x] use new format when generating openapi
  - [x] warnings if using new format with swagger
- [x] rewrite openapi_test.clj to use new format
- [x] update examples:
  - [x] http-swagger
  - [x] ring-malli-swagger
  - [x] ring-spec-swagger
- [x] update openapi.md
- [ ] ~update coercion.md~
- [x] update ring/coercion.md
- [ ] ~update Metosin blog post: https://www.metosin.fi/blog/openapi3/~

**Comment by ikitommi** [comment]
initial implementation (ignore whitespace to see the diff better): https://github.com/metosin/reitit/pull/628/files?w=1

**Comment by opqdonut** [comment]
I think all of this is done now!

**Comment by opqdonut** [comment]
Good question! I've opened a new issue about this: #759
